### ISSUE TITLE
Installation instructions need to be updated.

### ISSUE THREAD

**Issue by jjlow** [arosen93/mof_screen#8]
I attempted to install mof_screen and got the following error after the command "pip install -r requirements.txt"

___________Start of error message__________________
Obtaining rASE from git+https://github.com/arosen93/rASE#egg=rASE (from -r requirements.txt (line 1))
  Cloning https://github.com/arosen93/rASE to ./src/rase
  Running command git clone -q https://github.com/arosen93/rASE /lcrc/project/ACO2RDS/PyMOFScreen/mof_screen/src/rase
  Resolved https://github.com/arosen93/rASE to commit 23b007a14e42b1090618e3d73bbd57feed132ed1
  WARNING: Generating metadata for package rASE produced metadata for project name ase. Fix your #egg=rASE fragments.
WARNING: Discarding git+https://github.com/arosen93/rASE#egg=rASE. Requested ase from git+https://github.com/arosen93/rASE#egg=rASE (from -r requirements.txt (line 1)) has inconsistent name: filename has 'rase', but metadata has 'ase'
ERROR: Could not find a version that satisfies the requirement rase (unavailable) (from versions: 0.1.0)
ERROR: No matching distribution found for rase (unavailable)
____________End of error message

Is there a workaround to this error?

Thanks!

John Low, Argonne National Laboratory

**Comment by arosen93** [comment]
Hi John,

Thanks for reaching out about this. It looks like you can probably work around this error simply by cloning the rASE repo [here](https://github.com/arosen93/rASE) and `pip install .`'ing it as-is.

However, I must note that unfortunately the current `mof_screen` package is no longer being maintained, so I can't guarantee it will be fully functional as-is. I have shifted my efforts towards a new packaged called [QuAcc](https://github.com/arosen93/quacc), which includes [recipes](https://github.com/arosen93/quacc/blob/main/quacc/recipes/vasp/qmof.py) for screening MOFs analogous to `mof_screen`. It's still in development, so this is a bit of an awkward in-between period. That said, if there is anything I can do to help or if there are specific collaboration opportunities where screening MOFs with DFT might be useful for you or your team, don't hesitate to reach out.

**Comment by jjlow** [comment]
Andrew,

Thanks for the help.  I got mof_screen installed and I am running on the bundled examples.

I am planning to try QuAcc too.  The documentation for mof_screen seemed more complete.

I will send you an email from my anl.gov email about collaboration.

John Low, Argonne National Laboratory

**Comment by arosen93** [comment]
Glad to hear you get it installed. Hopefully it can be of some use. Yes, unfortunately I am still putting together the documentation for QuAcc. Not to add more codes to the list, but I do want to take a moment to share a mature and well-documented code [Atomate2](https://github.com/materialsproject/atomate2), which enables high-throughput DFT workflows (although is not specific to MOFs).
